# Generated by Django 3.1.4 on 2021-01-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('stormstats', '0001_initial'), ('stormstats', '0002_auto_20210122_1202'), ('stormstats', '0003_auto_20210122_1203')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('jersey', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('height', models.CharField(max_length=5)),
                ('weight', models.PositiveIntegerField()),
                ('group', models.CharField(max_length=12)),
                ('position', models.CharField(max_length=14)),
                ('birthplace', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SkaterOverallStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField()),
                ('games', models.PositiveIntegerField()),
                ('goals', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('pim', models.CharField(max_length=6)),
                ('plusmin', models.IntegerField()),
                ('toipg', models.CharField(max_length=6)),
                ('ppg', models.PositiveIntegerField()),
                ('ppa', models.PositiveIntegerField()),
                ('shg', models.PositiveIntegerField()),
                ('sha', models.PositiveIntegerField()),
                ('etoipg', models.CharField(max_length=6)),
                ('shtoipg', models.CharField(max_length=6)),
                ('pptoipg', models.CharField(max_length=6)),
                ('shots', models.PositiveIntegerField()),
                ('shotpct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fopct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blocks', models.PositiveIntegerField()),
                ('hits', models.PositiveIntegerField()),
                ('shifts', models.PositiveIntegerField()),
                ('gwg', models.PositiveIntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stormstats.player')),
            ],
            options={
                'unique_together': {('season', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('season', models.PositiveIntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('opponent', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
    ]
