# Generated by Django 3.1.4 on 2021-01-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('time', models.TimeField()),
            ],
        ),
    ]
