# Generated by Django 3.1.4 on 2021-02-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormstats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bp_lat',
            field=models.DecimalField(decimal_places=4, default=10.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='bp_long',
            field=models.DecimalField(decimal_places=4, default=10.0, max_digits=6),
            preserve_default=False,
        ),
    ]
