# Generated by Django 3.1.4 on 2021-01-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormstats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('jersey', models.IntegerField(max_length=2)),
                ('age', models.IntegerField(max_length=2)),
                ('height', models.CharField(max_length=5)),
                ('weight', models.IntegerField(max_length=3)),
                ('group', models.CharField(max_length=12)),
                ('position', models.CharField(max_length=14)),
                ('birthplace', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Game',
        ),
    ]
