# Generated by Django 3.1.4 on 2021-01-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormstats', '0001_squashed_0003_auto_20210122_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
