# Generated by Django 3.1.4 on 2021-01-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
