# Generated by Django 3.1.4 on 2021-02-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goaliegamestats',
            name='pim',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='skatergamestats',
            name='pim',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='skateroverallstats',
            name='pim',
            field=models.PositiveIntegerField(),
        ),
    ]
