# Generated by Django 3.1.4 on 2021-02-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormstats', '0002_auto_20210222_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bp_lat',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='player',
            name='bp_long',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
