# Generated by Django 3.1.4 on 2021-01-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormstats', '0002_auto_20210122_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
