# Generated by Django 3.1.4 on 2021-01-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormstats', '0002_auto_20210122_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
