on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  security_checks:
    runs-on: ubuntu-latest
    name: Execute python security check
    steps:
    - name: PyCharm Python Security Scanner
      uses: tonybaloney/pycharm-security@1.22.2
