name: Python Security Scan

on:
  pull_request:
    branches: 
      - master

jobs:
  security_checks:
    runs-on: ubuntu-latest
    name: Execute PyCharm Python Security Scanner Actions
    steps:
    - uses: actions/checkout@v1
    - name: Run Security Scanner
      uses: tonybaloney/pycharm-security@1.22.2
